apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: vault
  repo: https://helm.releases.hashicorp.com
  version: v0.30.0
  releaseName: vault
  namespace: vault
  valuesFile: values.yaml

resources:
- serviceaccount.yaml
- secret.yaml
