global:
  enabled: true
  tlsDisable: true

server:
  enabled: true
  standalone:
    enabled: true
    config: |
      storage "file" {
        path = "/vault/data"
      }

      listener "tcp" {
        address     = "0.0.0.0:8200"
        tls_disable = 1
      }

      ui = true
  dataStorage:
    enabled: true
    size: 8Gi
    storageClass: nfs-sc
  readinessProbe:
    enabled: true
  livenessProbe:
    enabled: true
  resources:
    requests:
      memory: 256Mi
      cpu: 250m
    limits:
      memory: 256Mi
      cpu: 250m
  ingress:
    enabled: true
    ingressClassName: traefik
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
    hosts:
    - host: vault.<path:secret/data/infra#domain>
      paths: []

injector:
  enabled: true

ui:
  enabled: true
