apiVersion: batch/v1
kind: CronJob
metadata:
  name: vault-unseal
  namespace: vault
spec:
  schedule: "*/10 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: vault-unsealer
            image: {{ .Values.cronjob.image.repository }}:{{ .Values.cronjob.image.tag }}
            command:
              - /bin/sh
              - -c
              - |
                echo "Waiting for the vault to be available..."
                for i in {1..30}; do
                  vault status > /dev/null 2>&1 && break
                  sleep 5
                done

                if vault status | grep -q 'Sealed.*false'; then
                  echo "Vault already unsealed, exiting."
                  exit 0
                fi

                echo "Vault is sealed, unsealing..."
                vault operator unseal "${KEY1}"
                vault operator unseal "${KEY2}"
                vault operator unseal "${KEY3}"
            env:
            - name: VAULT_ADDR
              value: {{ .Values.vault.server }}
            - name: KEY1
              valueFrom:
                secretKeyRef:
                  name: vault-unseal-secret
                  key: key1
            - name: KEY2
              valueFrom:
                secretKeyRef:
                  name: vault-unseal-secret
                  key: key2
            - name: KEY3
              valueFrom:
                secretKeyRef:
                  name: vault-unseal-secret
                  key: key3
